services:
  - type: web
    name: coffee-label-generator
    runtime: python
    buildCommand: "pipenv install --deploy --system"
    startCommand: "gunicorn --workers 1 --threads 8 --bind 0.0.0.0:$PORT app:app"
